#
# This is the default config used to instantiate hyperdrive if it is instantiated programmtically with no options eg:
#
# const hyperdrive = new Hyperdrive();
#

config: seg



# should we put "core" config here?
# hyperdrive:
#   config:
#   // list of installers
#   installers:

#   // Just OCLIF command objects, this is just a list of metadata
#   commands:
#     - {id: 'install', variant: 'lando-docker-engine', path:  }

#   plugins:
#     - pathtofunction -> gets config and returns plugin

#   // Final mods to commands, useful to add more options/args etc
#   mods: (?)
#     - {id: 'install', path: }
test: true
path: ./lib/hyperdrive.js
path2: /things/stuff/people
