core:
  engine: docker-desktop
  telemetry: true
  release-channel: stable

engines:
  # @TODO: how does this work loading wise? we need a way to translate these to absolute paths?
  docker-colima: hyperdrive://core/docker-colima
  docker-desktop: hyperdrive://core/docker-desktop
  docker-engine: hyperdrive://core/docker-engine

# @TODO: need to bump these to 3.6.6 once we release a lando with `lando hyperdrive`
lando:
  bin: lando
  install-default: "3.6.5" # @TODO: need to bump this once we release a lando with `lando hyperdrive`
  # @NOTE: below uses the satisfies syntax from https://www.npmjs.com/package/semver
  required-version: ">=3.6.5" # @TODO: need to bump this once we release a lando with `lando hyperdrive`

npm:
plugins:
updates:
  notify: true
