core:
  app: minapp
  debugspace: hyperdrive
  debug: false
  engine: docker-desktop
  id: hyperdrive
  lando: lando-cli
  product: hyperdrive
  release-channel: stable
  telemetry: true

  # this will force hyperdrive to use updated config from lando on every run. normally hyperdrive will use a
  # cached config that is generated on every lando run for version/plugin/config information.
  # you can use the hidden `lando --hyperdrive` command to regenerate this file.
  #
  # GENERALLY THIS IS FINE FOR MOST USE CASES.
  #
  # However, if you are running lando from source and modifying config that
  # hyperdrive uses, core plugin, etc it might make sense to enable this setting. Note that it comes with a ~10-20ms
  # performance hit and will override any app/pluginDir config you've set in hyperdrive
  auto-sync: false

# @TODO: what goes in here?
npm:

# @TODO: what goes in here?
plugins:
  # @NOTE: we will try to get this crom core.lando but you can override it here.
  # globalDir:

# @TODO: should this be in core?
updates:
  notify: true
