# core:
#   debug: false
#   engine: docker-desktop
#   id: hyperdrive
#   lando: lando-cli
#   product: hyperdrive
#   release-channel: stable
#   telemetry: true

#   # this will force hyperdrive to use updated config from lando on every run. normally hyperdrive will use a
#   # cached config that is generated on every lando run for version/plugin/config information.
#   # you can use the hidden `lando --hyperdrive` command to regenerate this file.
#   #
#   # GENERALLY THIS IS FINE FOR MOST USE CASES.
#   #
#   # However, if you are running lando from source and modifying config that
#   # hyperdrive uses, core plugin, etc it might make sense to enable this setting. Note that it comes with a ~10-20ms
#   # performance hit and will override any app/pluginDir config you've set in hyperdrive
#   auto-sync: false

# registry:
#   engine:
#     # @TODO: how does this work loading wise? we need a way to translate these to absolute paths?
#     docker-colima: hyperdrive://core/docker-colima
#     docker-desktop: hyperdrive://core/docker-desktop
#     docker-engine: hyperdrive://core/docker-engine
#   lando:
#     lando-cli: hyperdrive://core/lando-cli

# docker-desktop:
#   required-version: ">=3.6.5 && <=5.0.0"
#   supported-version: ">=3.6.5 && <=4.10.5"

# # @TODO: need to bump these to 3.6.6 once we release a lando with `lando hyperdrive`
# lando-cli:
#   bin: lando
#   install-default: "3.6.5" # @TODO: need to bump this once we release a lando with `lando hyperdrive`
#   # @NOTE: below uses the satisfies syntax from https://www.npmjs.com/package/semver
#   required-version: ">=3.6.5" # @TODO: need to bump this once we release a lando with `lando hyperdrive`

# npm:

# # @TODO: what goes in here?
# plugins:

# updates:
#   notify: true
