# THIS IS A COMMENT
name: hyperdrive-app-basics

# THIS IS A COMMENT 2
includes:
  # THIS IS A COMMENT
  - drupal

# THIS IS A COMMENT 4
plugins:
  # THIS IS A COMMENT
  "@lando/drupal": "^0.6.0"
  "@lando/apache": git://github.com/lando/apache.git#main
  "@lando/phpmyadmin": "0.6.0"
  "@lando/php": github:lando/php#main
  "@pirog/test-plugin": file:plugins/test-plugin

config:
  core:
    bob: thing
